### ISSUE TITLE
Is your repository issues connected to Taiga issues?

### ISSUE THREAD

**Issue by Blackedal** [Ninjansson/GrowUp#7]
Well... is it?

**Comment by Khamekaze** [comment]
Yes it is

**Comment by Blackedal** [comment]
If it is then this issue would show up in your Issues tab in Taiga. You need to webhook your repository in Taiga settings.

**Comment by miagruvman** [comment]
No it is not Johan. I have no idea who the hell Khamekaze is but he/she is not part of this project. We will connect it to Taiga asap! 
/ Kim

**Comment by ameliehellners** [comment]
Now it is!! :)! But only new issues will be shown in Taiga :(!
